"""add SupplierPhone table

Revision ID: 81bec74acab7
Revises: 7a4b72d1b2ad
Create Date: 2025-07-23 07:40:44.108085

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '81bec74acab7'
down_revision: Union[str, Sequence[str], None] = '7a4b72d1b2ad'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('supplier_phones',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=False),
    sa.Column('supplier_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['supplier_id'], ['suppliers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('phone')
    )
    op.drop_constraint(op.f('suppliers_phone_key'), 'suppliers', type_='unique')
    op.drop_column('suppliers', 'phone')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('suppliers', sa.Column('phone', sa.VARCHAR(length=20), autoincrement=False, nullable=False))
    op.create_unique_constraint(op.f('suppliers_phone_key'), 'suppliers', ['phone'], postgresql_nulls_not_distinct=False)
    op.drop_table('supplier_phones')
    # ### end Alembic commands ###
