"""update admin table and temp-admin table

Revision ID: 955bb8ddf61e
Revises: 145fd585aabd
Create Date: 2025-07-19 21:39:16.932996

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '955bb8ddf61e'
down_revision: Union[str, Sequence[str], None] = '145fd585aabd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('admins', sa.Column('is_root', sa.Boolean(), nullable=True))
    op.add_column('temp_admins', sa.Column('is_root', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('temp_admins', 'is_root')
    op.drop_column('admins', 'is_root')
    # ### end Alembic commands ###
