"""add thumbnail-id for product

Revision ID: c618ffd9a00b
Revises: e9ff26a5bebd
Create Date: 2025-07-21 10:02:49.028293

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c618ffd9a00b'
down_revision: Union[str, Sequence[str], None] = 'e9ff26a5bebd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('thumbnail_id', sa.String(), nullable=True))
    op.create_unique_constraint(None, 'products', ['thumbnail_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'products', type_='unique')
    op.drop_column('products', 'thumbnail_id')
    # ### end Alembic commands ###
