"""update purchase and product table

Revision ID: c7da9021d46c
Revises: db9bd5e95ebf
Create Date: 2025-08-07 15:31:11.911405

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c7da9021d46c'
down_revision: Union[str, Sequence[str], None] = 'db9bd5e95ebf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('products', 'quantity',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_column('products', 'unit_price')
    op.add_column('purchases', sa.Column('import_date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('purchases', 'import_date')
    op.add_column('products', sa.Column('unit_price', sa.NUMERIC(), autoincrement=False, nullable=False))
    op.alter_column('products', 'quantity',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
