"""update supplier table

Revision ID: f524cfb8d174
Revises: c618ffd9a00b
Create Date: 2025-07-22 09:06:56.589627

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f524cfb8d174'
down_revision: Union[str, Sequence[str], None] = 'c618ffd9a00b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('purchases_supplier_id_fkey'), 'purchases', type_='foreignkey')
    op.create_foreign_key(None, 'purchases', 'suppliers', ['supplier_id'], ['id'], ondelete='SET NULL')
    op.alter_column('suppliers', 'address',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.create_unique_constraint(None, 'suppliers', ['email'])
    op.create_unique_constraint(None, 'suppliers', ['phone'])
    op.create_unique_constraint(None, 'suppliers', ['name'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'suppliers', type_='unique')
    op.drop_constraint(None, 'suppliers', type_='unique')
    op.drop_constraint(None, 'suppliers', type_='unique')
    op.alter_column('suppliers', 'address',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.drop_constraint(None, 'purchases', type_='foreignkey')
    op.create_foreign_key(op.f('purchases_supplier_id_fkey'), 'purchases', 'suppliers', ['supplier_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###
