"""update product and purchase

Revision ID: fa2b7bc5804b
Revises: 84c2d9d994db
Create Date: 2025-07-24 14:35:23.607303

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fa2b7bc5804b'
down_revision: Union[str, Sequence[str], None] = '84c2d9d994db'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('unit_price', sa.Numeric(scale=2), nullable=False))
    op.drop_column('products', 'last_unit_price')
    op.drop_column('products', 'curr_unit_price')
    op.add_column('purchase_products', sa.Column('quantity', sa.Integer(), nullable=False))
    op.drop_column('purchase_products', 'purchase_quantity')
    op.add_column('purchases', sa.Column('is_update_product', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('purchases', 'is_update_product')
    op.add_column('purchase_products', sa.Column('purchase_quantity', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_column('purchase_products', 'quantity')
    op.add_column('products', sa.Column('curr_unit_price', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=False))
    op.add_column('products', sa.Column('last_unit_price', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=True))
    op.drop_column('products', 'unit_price')
    # ### end Alembic commands ###
